# Generated by Django 4.2.3 on 2023-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=300),
        ),
    ]
